# Game Constants for R-TYPE clone

# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors (R, G, B)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (50, 100, 255)
RED = (255, 50, 50)
ORANGE = (255, 150, 0)
GREEN = (50, 255, 50)
YELLOW = (255, 255, 0)
DARK_GRAY = (40, 40, 40)
LIGHT_GRAY = (200, 200, 200)
CYAN = (0, 255, 255)
PURPLE = (128, 0, 128)  # 砲台用

# Player settings
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 20
PLAYER_SPEED = 5
PLAYER_MAX_LIVES = 3
PLAYER_INVINCIBILITY_TIME = 2000  # milliseconds

# Force settings
FORCE_SIZE = 29
FORCE_ATTACH_DISTANCE = 35
FORCE_DETACHED_SPEED = 2

# Force states
FORCE_ATTACHED_FRONT = 0
FORCE_ATTACHED_BACK = 1
FORCE_DETACHED = 2

# Force positions (for 3-Force system)
FORCE_POSITION_CENTER = 0
FORCE_POSITION_TOP = 1
FORCE_POSITION_BOTTOM = 2

# Force vertical offset for top/bottom positions
FORCE_VERTICAL_OFFSET = 40  # pixels above/below center

# Bullet settings
BULLET_WIDTH = 8
BULLET_HEIGHT = 4
BULLET_SPEED = 5
BULLET_DAMAGE = 1

# Charge shot settings
CHARGE_LEVEL_1_TIME = 30  # frames (0.5 seconds at 60 FPS)
CHARGE_LEVEL_2_TIME = 60  # frames (1.0 seconds)
CHARGE_LEVEL_3_TIME = 90  # frames (1.5 seconds)

CHARGE_LEVEL_1_SIZE = 2
CHARGE_LEVEL_2_SIZE = 3
CHARGE_LEVEL_3_SIZE = 5

CHARGE_LEVEL_1_DAMAGE = 2
CHARGE_LEVEL_2_DAMAGE = 3
CHARGE_LEVEL_3_DAMAGE = 10

CHARGE_LEVEL_2_PIERCE = 2
CHARGE_LEVEL_3_PIERCE = 3

# Enemy settings
ENEMY_SPAWN_INTERVAL = 90  # frames (1.5 seconds)

# Enemy types
ENEMY_TYPE_STRAIGHT = 0
ENEMY_TYPE_WAVE = 1
ENEMY_TYPE_CHARGE = 2
ENEMY_TYPE_TANK = 3
ENEMY_TYPE_TURRET = 4  # 新規：地形固定砲台
ENEMY_TYPE_BOSS_1 = 5  # Wave 1ボス
ENEMY_TYPE_BOSS_2 = 6  # Wave 2ボス
ENEMY_TYPE_BOSS_3 = 7  # Wave 3ボス

# Enemy stats (HP, Speed, Score)
ENEMY_STRAIGHT_HP = 1
ENEMY_STRAIGHT_SPEED = 3
ENEMY_STRAIGHT_SCORE = 100

ENEMY_WAVE_HP = 2
ENEMY_WAVE_SPEED = 2
ENEMY_WAVE_SCORE = 200

ENEMY_CHARGE_HP = 3
ENEMY_CHARGE_SPEED = 4
ENEMY_CHARGE_SCORE = 300

ENEMY_TANK_HP = 5
ENEMY_TANK_SPEED = 1
ENEMY_TANK_SCORE = 500

ENEMY_TURRET_HP = 3
ENEMY_TURRET_SPEED = 0  # 移動しない
ENEMY_TURRET_SCORE = 150
ENEMY_TURRET_SHOOT_INTERVAL = 120  # 2秒
TURRET_SIZE = 60  # 3倍に拡大（20 → 60）

# Boss stats
BOSS_1_HP = 45  # Wave 1ボス（通常敵の30倍）
BOSS_1_SPEED = 1
BOSS_1_SCORE = 1000
BOSS_1_SIZE = 80
BOSS_1_SHOOT_INTERVAL = 60  # 1秒ごと

BOSS_2_HP = 75  # Wave 2ボス
BOSS_2_SPEED = 1.5
BOSS_2_SCORE = 2000
BOSS_2_SIZE = 100
BOSS_2_SHOOT_INTERVAL = 45  # 0.75秒ごと

BOSS_3_HP = 110  # Wave 3ボス
BOSS_3_SPEED = 2
BOSS_3_SCORE = 3000
BOSS_3_SIZE = 120
BOSS_3_SHOOT_INTERVAL = 30  # 0.5秒ごと

# Wave 4 Boss spawn settings
WAVE4_MAX_SIMULTANEOUS_BOSSES = 3      # 最大同時ボス数
WAVE4_MIN_BOSS_INTERVAL = 600          # 最低出現間隔（フレーム）= 10秒
WAVE4_INITIAL_BOSS_CHANCE = 0.05       # 初期出現確率（5%）
WAVE4_MAX_BOSS_CHANCE = 0.25           # 最大出現確率（25%）
WAVE4_DIFFICULTY_RAMP_TIME = 7200      # 難易度上昇期間（フレーム）= 120秒

# Enemy bullet settings (タイプ別)
ENEMY_BULLET_SPEED_WAVE = 3      # WAVE敵の弾速（遅め、狙い撃ち弾があるため）
ENEMY_BULLET_SPEED_TANK = 4      # TANK敵の弾速（中速、3方向拡散のため）
ENEMY_BULLET_SPEED_TURRET = 2   # TURRET砲台の弾速（速め、固定砲台のため）

# 共通設定
ENEMY_BULLET_SPEED = 5  # 後方互換性のため残す（STRAIGHT/CHARGE用）
ENEMY_BULLET_WIDTH = 6
ENEMY_BULLET_HEIGHT = 6

# Powerup settings
POWERUP_SIZE = 20
POWERUP_SPEED = 2

POWERUP_TYPE_FORCE = 0
POWERUP_TYPE_SPEED = 1
POWERUP_TYPE_POWER = 2
POWERUP_TYPE_3WAY = 3  # 新規：3-Way武器

# Player weapon types
WEAPON_TYPE_NORMAL = 0  # 水平射撃のみ
WEAPON_TYPE_3WAY = 1    # 3方向射撃

# Player weapon fire rates
WEAPON_NORMAL_DELAY = 10   # frames
WEAPON_3WAY_DELAY = 15  #frames (1.5x slower to balance 3 bullets)

# 3-Way settings
WAY3_ANGLE_DEG = 40  # 度（上下の弾丸の角度）

# Powerup duration settings
POWERUP_DURATION_MULTIPLIER = 2  # パワーアップ効果時間の倍率（平均出現間隔の何倍か）
POWER_EFFECT_DURATION = 2400  # POWER効果の持続時間（フレーム数） = 30秒 × 2 = 60秒
WAY3_EFFECT_DURATION = 2400   # 3-WAY効果の持続時間（フレーム数） = 30秒 × 2 = 60秒

# Explosion settings
EXPLOSION_DURATION = 20  # frames
EXPLOSION_PARTICLE_COUNT = 8

# Wave system
WAVE_1_START = 0
WAVE_1_END = 1800  # 30 seconds
WAVE_2_START = 1800
WAVE_2_END = 3600  # 60 seconds
WAVE_3_START = 3600
WAVE_3_END = 5400  # 90 seconds
WAVE_4_START = 5400

# Sound settings
SOUND_ENABLED = True
SOUND_VOLUME_MASTER = 0.5
SOUND_SAMPLE_RATE = 22050

# Terrain settings
TERRAIN_SCROLL_SPEED = 2
TERRAIN_SEGMENT_WIDTH = 100
TERRAIN_SPAWN_INTERVAL = 50  # frames
TERRAIN_COLOR = (80, 80, 100)  # 青灰色
TERRAIN_EDGE_COLOR = (120, 120, 150)  # 明るい縁
TERRAIN_DAMAGE_COOLDOWN = 30  # 地形ダメージのクールダウン（0.5秒）

# Terrain pattern durations (frames)
PATTERN_DURATION_EASY = 600  # 10秒
PATTERN_DURATION_NORMAL = 480  # 8秒
PATTERN_DURATION_HARD = 360  # 6秒

# Aimed bullet settings
AIMED_BULLET_CHANCE_WAVE = 0.3  # WAVE敵の狙い撃ち確率

# Turret spawn chances per wave
TURRET_SPAWN_CHANCE_WAVE_1 = 0.0
TURRET_SPAWN_CHANCE_WAVE_2 = 0.2
TURRET_SPAWN_CHANCE_WAVE_3 = 0.3
TURRET_SPAWN_CHANCE_WAVE_4 = 0.4

# Turret shoot intervals per wave (frames)
TURRET_INTERVAL_WAVE_2 = 120  # 2秒
TURRET_INTERVAL_WAVE_3 = 90   # 1.5秒
TURRET_INTERVAL_WAVE_4 = 60   # 1秒
