# Game Constants for R-TYPE clone

# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors (R, G, B)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (50, 100, 255)
RED = (255, 50, 50)
ORANGE = (255, 150, 0)
GREEN = (50, 255, 50)
YELLOW = (255, 255, 0)
DARK_GRAY = (40, 40, 40)
LIGHT_GRAY = (200, 200, 200)
CYAN = (0, 255, 255)

# Player settings
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 20
PLAYER_SPEED = 5
PLAYER_MAX_LIVES = 3
PLAYER_INVINCIBILITY_TIME = 2000  # milliseconds

# Force settings
FORCE_SIZE = 40
FORCE_ATTACH_DISTANCE = 30
FORCE_DETACHED_SPEED = 2

# Force states
FORCE_ATTACHED_FRONT = 0
FORCE_ATTACHED_BACK = 1
FORCE_DETACHED = 2

# Bullet settings
BULLET_WIDTH = 8
BULLET_HEIGHT = 4
BULLET_SPEED = 10
BULLET_DAMAGE = 1

# Charge shot settings
CHARGE_LEVEL_1_TIME = 30  # frames (0.5 seconds at 60 FPS)
CHARGE_LEVEL_2_TIME = 60  # frames (1.0 seconds)
CHARGE_LEVEL_3_TIME = 90  # frames (1.5 seconds)

CHARGE_LEVEL_1_SIZE = 2
CHARGE_LEVEL_2_SIZE = 3
CHARGE_LEVEL_3_SIZE = 5

CHARGE_LEVEL_1_DAMAGE = 2
CHARGE_LEVEL_2_DAMAGE = 3
CHARGE_LEVEL_3_DAMAGE = 5

CHARGE_LEVEL_2_PIERCE = 2
CHARGE_LEVEL_3_PIERCE = 999  # Infinite pierce

# Enemy settings
ENEMY_SPAWN_INTERVAL = 90  # frames (1.5 seconds)

# Enemy types
ENEMY_TYPE_STRAIGHT = 0
ENEMY_TYPE_WAVE = 1
ENEMY_TYPE_CHARGE = 2
ENEMY_TYPE_TANK = 3

# Enemy stats (HP, Speed, Score)
ENEMY_STRAIGHT_HP = 1
ENEMY_STRAIGHT_SPEED = 3
ENEMY_STRAIGHT_SCORE = 100

ENEMY_WAVE_HP = 2
ENEMY_WAVE_SPEED = 2
ENEMY_WAVE_SCORE = 200

ENEMY_CHARGE_HP = 3
ENEMY_CHARGE_SPEED = 4
ENEMY_CHARGE_SCORE = 300

ENEMY_TANK_HP = 5
ENEMY_TANK_SPEED = 1
ENEMY_TANK_SCORE = 500

# Enemy bullet settings
ENEMY_BULLET_SPEED = 5
ENEMY_BULLET_WIDTH = 6
ENEMY_BULLET_HEIGHT = 6

# Powerup settings
POWERUP_SIZE = 20
POWERUP_SPEED = 2

POWERUP_TYPE_FORCE = 0
POWERUP_TYPE_SPEED = 1
POWERUP_TYPE_POWER = 2

# Explosion settings
EXPLOSION_DURATION = 20  # frames
EXPLOSION_PARTICLE_COUNT = 8

# Wave system
WAVE_1_START = 0
WAVE_1_END = 1800  # 30 seconds
WAVE_2_START = 1800
WAVE_2_END = 3600  # 60 seconds
WAVE_3_START = 3600
WAVE_3_END = 5400  # 90 seconds
WAVE_4_START = 5400

# Sound settings
SOUND_ENABLED = True
SOUND_VOLUME_MASTER = 0.5
SOUND_SAMPLE_RATE = 22050

# Terrain settings
TERRAIN_SCROLL_SPEED = 2
TERRAIN_SEGMENT_WIDTH = 100
TERRAIN_SPAWN_INTERVAL = 50  # frames
TERRAIN_COLOR = (80, 80, 100)  # 青灰色
TERRAIN_EDGE_COLOR = (120, 120, 150)  # 明るい縁
TERRAIN_DAMAGE_COOLDOWN = 30  # 地形ダメージのクールダウン（0.5秒）

# Terrain pattern durations (frames)
PATTERN_DURATION_EASY = 600  # 10秒
PATTERN_DURATION_NORMAL = 480  # 8秒
PATTERN_DURATION_HARD = 360  # 6秒
